/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PlayGameIdRouteImport } from './routes/play.$gameId'
import { Route as CategoryCategoryRouteImport } from './routes/category.$category'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as AdminPlayersRouteImport } from './routes/admin/players'
import { Route as AdminLoginLogsRouteImport } from './routes/admin/login-logs'
import { Route as AdminGamesRouteImport } from './routes/admin/games'
import { Route as AdminPlayerIdRouteImport } from './routes/admin/player.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PlayGameIdRoute = PlayGameIdRouteImport.update({
  id: '/play/$gameId',
  path: '/play/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginLogsRoute = AdminLoginLogsRouteImport.update({
  id: '/login-logs',
  path: '/login-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayerIdRoute = AdminPlayerIdRouteImport.update({
  id: '/player/$id',
  path: '/player/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/login-logs': typeof AdminLoginLogsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/player/$id': typeof AdminPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/login-logs': typeof AdminLoginLogsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/player/$id': typeof AdminPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/login-logs': typeof AdminLoginLogsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/player/$id': typeof AdminPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/profile'
    | '/register'
    | '/settings'
    | '/wallet'
    | '/admin/games'
    | '/admin/login-logs'
    | '/admin/players'
    | '/admin/transactions'
    | '/category/$category'
    | '/play/$gameId'
    | '/admin/'
    | '/admin/player/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/settings'
    | '/wallet'
    | '/admin/games'
    | '/admin/login-logs'
    | '/admin/players'
    | '/admin/transactions'
    | '/category/$category'
    | '/play/$gameId'
    | '/admin'
    | '/admin/player/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/profile'
    | '/register'
    | '/settings'
    | '/wallet'
    | '/admin/games'
    | '/admin/login-logs'
    | '/admin/players'
    | '/admin/transactions'
    | '/category/$category'
    | '/play/$gameId'
    | '/admin/'
    | '/admin/player/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  WalletRoute: typeof WalletRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  PlayGameIdRoute: typeof PlayGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/play/$gameId': {
      id: '/play/$gameId'
      path: '/play/$gameId'
      fullPath: '/play/$gameId'
      preLoaderRoute: typeof PlayGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login-logs': {
      id: '/admin/login-logs'
      path: '/login-logs'
      fullPath: '/admin/login-logs'
      preLoaderRoute: typeof AdminLoginLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/player/$id': {
      id: '/admin/player/$id'
      path: '/player/$id'
      fullPath: '/admin/player/$id'
      preLoaderRoute: typeof AdminPlayerIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminGamesRoute: typeof AdminGamesRoute
  AdminLoginLogsRoute: typeof AdminLoginLogsRoute
  AdminPlayersRoute: typeof AdminPlayersRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPlayerIdRoute: typeof AdminPlayerIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGamesRoute: AdminGamesRoute,
  AdminLoginLogsRoute: AdminLoginLogsRoute,
  AdminPlayersRoute: AdminPlayersRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPlayerIdRoute: AdminPlayerIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  WalletRoute: WalletRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  PlayGameIdRoute: PlayGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
